### ISSUE TITLE
hardware_camera cam_microsoft.launch problem

### ISSUE THREAD

**Issue by naishadhparmar** [AUV-IITK/fourtran#18]
There is a problem in the node name vs the pre-remapped image topic name. I'll solve this tomorrow. Without this, vision_layer will not work.

**Comment by Mayankm96** [comment]
Don't change the topic name in the `hardware_camera` package. Instead, change it in the vision package. The earlier names were too long so it became awkward to remember them. Thus, I changed the convention to `package_name/name` only.

**Comment by Suryansh470** [comment]
@Mayankm96 we need to remap the topic at the place only where we are specifying the ROS driver launch file so it will be specified in ```hardware_camera``` only

**Comment by Mayankm96** [comment]
@naishadhparmar Is this fixed now?

**Comment by Mayankm96** [comment]
Fixed by PR #21
