### ISSUE TITLE
Using existing ROS drivers to publish images instead of OpenCV

### ISSUE THREAD

**Issue by Mayankm96** [AUV-IITK/fourtran#2]
The [lines 43-47](https://github.com/AUV-IITK/fourtran/blob/master/vision_layer/buoy_processing/src/buoy_processing.cpp#L43-L47) in the `buoy_processing` node uses the `highgui` library to capture video frames. Instead of that [`uvc_camera`](http://wiki.ros.org/uvc_camera) or [`usb_cam`](http://wiki.ros.org/usb_cam) packages can be used. These need to added to the `hardware_layer` and the code needs to be changed appropriately.

**Comment by Mayankm96** [comment]
@Suryansh470 @naishadhparmar Updates on this? 

I have started the hardware_layer in the [`mayank_arduino_devel`](https://github.com/AUV-IITK/fourtran/tree/mayank-arduino-devel) branch. feel free to add this to that and send a pull request.

**Comment by Suryansh470** [comment]
https://rosstitchernode.wordpress.com/2014/06/05/ros-and-opencv-with-usb_cam/

Check this out

**Comment by Suryansh470** [comment]
@Mayankm96 the ROS drivers have been successfully implemented using libuvc_camera/usb_cam both .... by tonight @naishadhparmar and I will send a Pull request !!

**Comment by Mayankm96** [comment]
This has been dealt with in the PR #10.

**Comment by Mayankm96** [comment]
I have made a few changes and cleaning to the PR. The parameters can now be loaded using a config file.
