### ISSUE TITLE
Using custom header files for writing hardware_arduino node

### ISSUE THREAD

**Issue by Suryansh470** [AUV-IITK/fourtran#3]

**Comment by Mayankm96** [comment]
Any references to this?

**Comment by Suryansh470** [comment]
The hardware_arduino written for Varun can be considered as one of the reference.......

**Comment by Mayankm96** [comment]
If you're referring to the file [here](https://github.com/AUV-IITK/auv2016/blob/master/hardware_layer/hardware_arduino/src/MS5837.h), that was given by the company to use the depth sensor.
