### ISSUE TITLE
Using messages with Header information for various tasks

### ISSUE THREAD

**Issue by Mayankm96** [AUV-IITK/fourtran#9]
So far we have been using the `std_msgs` and other message formats that ROS provides. Typically, it might be of interest to use messages with [`header`](http://docs.ros.org/lunar/api/std_msgs/html/msg/Header.html) information as well. I am saying so because having information like when a particular data was published is useful when subscribing to multiple topics to carry out an action so that data retrieved is in-sync. For instance, in stereo vision, we need to have image messages published in the same instant by the sensors. 

For buoy task, the message should of the form  [`PointStamped`](http://docs.ros.org/api/geometry_msgs/html/msg/PointStamped.html) instead of [`Float32MultiArray`](http://docs.ros.org/api/std_msgs/html/msg/Float32MultiArray.html). You can also look into [`tf2`](http://wiki.ros.org/tf2) as an alternate option. This would allow also visualization of the measured buoy location in `rviz` using [markers](http://wiki.ros.org/rviz/DisplayTypes/Marker).

**Comment by naishadhparmar** [comment]
@Mayankm96 I have used [`PointStamped`](http://docs.ros.org/api/geometry_msgs/html/msg/PointStamped.html) in PR #10. We can consider this closed.

**Comment by Suryansh470** [comment]
Since the geometry messages is already used by @naishadhparmar in the vision code ... so we can consider this issue to be closed
